server.port=${SERVER_PORT:9004}
spring.application.name=notification-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:9007/leave_tracker}
spring.datasource.username=${DB_USERNAME:leave_user}
spring.datasource.password=${DB_PASSWORD:leave_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:9009}
spring.rabbitmq.username=${RABBIT_USERNAME:leave_user}
spring.rabbitmq.password=${RABBIT_PASSWORD:leave_pass}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:9005/eureka/}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_URL:http://localhost:9010/api/v2/spans}
management.endpoints.web.exposure.include=health,info
