filebeat.inputs:
  - type: filestream
    id: employee-leave-docker-logs
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~
    prospector.scanner.symlinks: true

processors:
  - add_docker_metadata:
      host: unix:///var/run/docker.sock
  - add_fields:
      target: project
      fields:
        name: employee-leave-tracker

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
