input {
  beats {
    port => 5044
  }
}

filter {
  if [message] {
    mutate {
      add_field => {
        "project" => "employee-leave-tracker"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "employee-leave-tracker-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
